USE [master]
GO

/****** Object:  Database [XanoHub]    Script Date: 10/25/2015 7:12:27 PM ******/
CREATE DATABASE [XanoHub]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'XanoHub', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\XanoHub.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'XanoHub_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\XanoHub_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [XanoHub] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [XanoHub].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [XanoHub] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [XanoHub] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [XanoHub] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [XanoHub] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [XanoHub] SET ARITHABORT OFF 
GO

ALTER DATABASE [XanoHub] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [XanoHub] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [XanoHub] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [XanoHub] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [XanoHub] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [XanoHub] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [XanoHub] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [XanoHub] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [XanoHub] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [XanoHub] SET  DISABLE_BROKER 
GO

ALTER DATABASE [XanoHub] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [XanoHub] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [XanoHub] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [XanoHub] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [XanoHub] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [XanoHub] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [XanoHub] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [XanoHub] SET RECOVERY FULL 
GO

ALTER DATABASE [XanoHub] SET  MULTI_USER 
GO

ALTER DATABASE [XanoHub] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [XanoHub] SET DB_CHAINING OFF 
GO

ALTER DATABASE [XanoHub] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [XanoHub] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [XanoHub] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [XanoHub] SET  READ_WRITE 
GO


